# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shop.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'shop.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nshop.proto\x12\x04shop\"7\n\x0fPurchaseRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"8\n\x10PurchaseResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x13\n\x0btotal_price\x18\x02 \x01(\x05\"8\n\x0ePaymentRequest\x12\x16\n\x0epayment_method\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x02\"3\n\x0fPaymentResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\"4\n\x0cOrderRequest\x12$\n\x05items\x18\x01 \x03(\x0b\x32\x15.shop.PurchaseRequest\"L\n\rOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12)\n\tpurchases\x18\x02 \x03(\x0b\x32\x16.shop.PurchaseResponse\"\x1c\n\tProductId\x12\x0f\n\x07product\x18\x01 \x01(\t\";\n\x12ProductDescription\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\x10\n\x08quentity\x18\x02 \x01(\x05\x32\xfc\x01\n\x0bShopService\x12=\n\x0cPurchaseItem\x12\x15.shop.PurchaseRequest\x1a\x16.shop.PurchaseResponse\x12:\n\x0bMakePayment\x12\x14.shop.PaymentRequest\x1a\x15.shop.PaymentResponse\x12\x35\n\nPlaceOrder\x12\x12.shop.OrderRequest\x1a\x13.shop.OrderResponse\x12;\n\x0eGetProductInfo\x12\x0f.shop.ProductId\x1a\x18.shop.ProductDescriptionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shop_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PURCHASEREQUEST']._serialized_start=20
  _globals['_PURCHASEREQUEST']._serialized_end=75
  _globals['_PURCHASERESPONSE']._serialized_start=77
  _globals['_PURCHASERESPONSE']._serialized_end=133
  _globals['_PAYMENTREQUEST']._serialized_start=135
  _globals['_PAYMENTREQUEST']._serialized_end=191
  _globals['_PAYMENTRESPONSE']._serialized_start=193
  _globals['_PAYMENTRESPONSE']._serialized_end=244
  _globals['_ORDERREQUEST']._serialized_start=246
  _globals['_ORDERREQUEST']._serialized_end=298
  _globals['_ORDERRESPONSE']._serialized_start=300
  _globals['_ORDERRESPONSE']._serialized_end=376
  _globals['_PRODUCTID']._serialized_start=378
  _globals['_PRODUCTID']._serialized_end=406
  _globals['_PRODUCTDESCRIPTION']._serialized_start=408
  _globals['_PRODUCTDESCRIPTION']._serialized_end=467
  _globals['_SHOPSERVICE']._serialized_start=470
  _globals['_SHOPSERVICE']._serialized_end=722
# @@protoc_insertion_point(module_scope)
